### ISSUE TITLE
things in transports should (optionally) work in parallel

### ISSUE THREAD

**Issue by jurajsimbs** [BohemiaInteractive/bi-logger#1]
scenario:  
I'm using fluentd but at least error logs should be collected also on the local fs because:  
- fluentd can be down
- logs are collected to elastic (or mongo, whatever... ) and that index can be damaged and/or destroyed easily because of an application error (easily - somebody forget a console.log somewhere)
- parsing error in fluentd

**Comment by fogine** [comment]
From readme:
> That means you can effectivelly log messages to more than one transport at the time given that two or more transports share same priority value.
